trigger: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- template: template-pr.yml
  parameters:
    buildProjects:
      - Microsoft.OneWeek.Hack.Microids.MessageRouter/Microsoft.OneWeek.Hack.Microids.MessageRouter.csproj
    testProjects:
      - Microsoft.OneWeek.Hack.Microids.MessageRouter.Tests/Microsoft.OneWeek.Hack.Microids.MessageRouter.Tests.csproj
