apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestrator
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: orchestrator
  template:
    metadata:
      labels:
        app: orchestrator
    spec:
      containers:
      - image: {{ .Values.image.repository }}/orchestrator:{{ .Values.image.tag}}
        name: orchestrator
        env:
        - name: "GENERATE_MESSAGES_EVERY"
          value: "{{ .Values.GENERATE_MESSAGES_EVERY }}"
        - name: "NUM_MESSAGES_EACH_GENERATION"
          value: "{{ .Values.NUM_MESSAGES_EACH_GENERATION }}"
        - name: "CACHE_GRPC_ENDPOINT"
          value: "{{ .Values.CACHE_GRPC_ENDPOINT }}"
        - name: "APPINSIGHTS_KEY"
          valueFrom:
            secretKeyRef:
              name: appinsightskey
              key: APPINSIGHTS_KEY
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 1
            memory: 2G
      tolerations:
      - key: "sku"
        operator: "Equal"
        value: "orchestrator"
        effect: "NoSchedule"