apiVersion: apps/v1
kind: Deployment
metadata:
  name: iotdevice
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: iotdevice
  template:
    metadata:
      labels:
        app: iotdevice
    spec:
      containers:
      - image: {{ .Values.image.repository }}/iotdevice:{{ .Values.image.tag}}
        name: iotdevice
        env:
        - name: "APPINSIGHTS_KEY"
          valueFrom:
            secretKeyRef:
              name: appinsightskey
              key: APPINSIGHTS_KEY
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 1
            memory: 2G
      tolerations:
      - key: "sku"
        operator: "Equal"
        value: "cache"
        effect: "NoSchedule"