apiVersion: apps/v1
kind: Deployment
metadata:
  name: iotdevice
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: iotdevice
  template:
    metadata:
      labels:
        app: iotdevice
    spec:
      containers:
      - image: {{ .Values.image.repository }}/iotdevice:{{ .Values.image.tag}}
        name: iotdevice
        env:
        - name: "PORT"
          value: "{{ .Values.PORT }}"
      tolerations:
      - key: "sku"
        operator: "Equal"
        value: "cache"
        effect: "NoSchedule"